# Generated by Django 5.0.2 on 2024-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
