# Generated by Django 5.0.2 on 2024-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_wishlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.listing'),
        ),
    ]
